### ISSUE TITLE
Problem: 0.5 testnet not yet deployed and documented

### ISSUE THREAD

**Issue by tomtau** [crypto-com/thaler-docs#131]
- [ ] @devashishdxt @lezzokafka @allthatjazzleo: new consensus pub keys + wallets + genesis file (ideally the existing 0.3 validators will start with their addresses allocated enough bonded stake, so only "nodejoin" is required)
- [ ] @allthatjazzleo : initial council nodes (validators) + full node (query) deployment (+ new monitoring? alerts?)
- [ ] @lezzokafka @allthatjazzleo : testing node join, jailing etc.
- [ ] if all goes good, @tomtau @lezzokafka : update docs + quick notification on Gitter + update preparation
- [ ] @calvinaco @foreseaz : tx bot + existing explorer quick changes
- [ ] if all went fine, @allthatjazzleo : decommission the 0.3 testnet by May 8?

**Comment by lezzokafka** [comment]
> * [ ]  if all goes good, @tomtau @lezzokafka : update docs + quick notification on Gitter + update preparation

Draft for the docs update: #133

**Comment by tomtau** [comment]
to be decommissioned by May 15?

**Comment by allthatjazzleo** [comment]
> to be decommissioned by May 15?
Some of testnet 3.0 have been decommissioned.
Still I have one node I need to confirm with @devashishdxt to decommission

**Comment by allthatjazzleo** [comment]
all testnet 3.0 were decommissioned @tomtau
